name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phpunit:
    strategy:
      matrix:
        php: ['8.0']

    runs-on: ubuntu-latest

    steps:
      - name: Set php version
        uses: shivammathur/setup-php@v2
        with:
          tools: composer:v2
          php-version: ${{ matrix.php }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Composer update
        run: composer update

      - name: Composer dependencies
        run: composer install --no-ansi --no-interaction --no-suggest --no-progress --prefer-dist

      - name: Run Testsuite
        run: composer test
